# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 04:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20170713_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['post_date']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='author',
            name='lastname',
        ),
        migrations.AddField(
            model_name='author',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(help_text='Enter your bio details here.', max_length=400),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Enter comment about blog here.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Enter your blog text here.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
