# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170715_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_post',
            new_name='post',
        ),
    ]
